### ISSUE TITLE
ConfigureBackchannelHttpClient fails

### ISSUE THREAD

**Issue by benaadams** [IdentityModel/IdentityModel.AspNetCore#10]
In ASP.NET Core 3.0 if you use
```csharp
services.AddTokenManagement()
    .ConfigureBackchannelHttpClient(client =>
    {
        client.Timeout = TimeSpan.FromSeconds(30);
    });
```
it fails with 
```
System.InvalidOperationException: 
'The HttpClient factory already has a registered client with the type 'IdentityModel.AspNetCore.TokenEndpointService'. 
Client types must be unique. 
Consider using inheritance to create multiple unique types with the same API surface.'
```
Because both `AddTokenManagement`
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/339d8c1d981e7acd3e607684830e09adeb8a9572/src/TokenManagement/TokenManagementServiceCollectionExtensions.cs#L25
and `ConfigureBackchannelHttpClient`
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/339d8c1d981e7acd3e607684830e09adeb8a9572/src/TokenManagement/TokenManagementBuilder.cs#L44

Register `services.AddHttpClient<TokenEndpointService>`

**Comment by leastprivilege** [comment]
Yes I know - I opened an issue. 

https://github.com/aspnet/Extensions/issues/2077

In IdentityServer we worked around it like this

https://github.com/IdentityServer/IdentityServer4/blob/features%2Faspnetcore3/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs#L366-L390

Any other idea?

**Comment by benaadams** [comment]
ASP.NET Core probably needs and .AddOrUpdate/Replace method?

**Comment by leastprivilege** [comment]
Something like this...too late for 3.0.

**Comment by leastprivilege** [comment]
I added a helper method.
