### ISSUE TITLE
"Unable to create the SignatureProvider" when using HMAC 256

### ISSUE THREAD

**Issue by mooreds** [IdentityModel/IdentityModel.AspNetCore#102]
Hiya,

Even though HMAC is listed under the supported algorithms here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Supported-Algorithms

when I try to use HMAC for code (basically just the sample app code against a FusionAuth IdP), I get an exception:

```
Exceptions caught:
 'System.NotSupportedException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'HS256', SecurityKey: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey, KeyId: 'T06oiDoC5J_5OFCoFT-MSMsoTuY', InternalId: 'db1d80f3-2b6c-419c-9b4a-7aa45659770a'.'
 is not supported. The list of supported algorithms is available here: https://aka.ms/IdentityModel/supported-algorithms
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForVerifying(SecurityKey key, String algorithm)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(Byte[] encodedBytes, Byte[] signature, SecurityKey key, String algorithm, TokenValidationParameters validationParameters)
```

If I use an RSA key to sign my JWTs, it works swimmingly.

I googled around a bit and couldn't find a good way to update the SignatureProvider, except this post, which seemed overkill: https://www.scottbrady91.com/C-Sharp/Supporting-Custom-JWT-Signing-Algorithms-in-dotnet-Core

Any suggestions on other things I should google? 

Thanks!

**Comment by leastprivilege** [comment]
no. sorry. Don't use symmetric keys is the easy answer.

**Comment by mooreds** [comment]
Thanks! I'll close if that's the right path forward. :)
