### ISSUE TITLE
Nuget package release cycle

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [IdentityModel/IdentityModel.AspNetCore#123]
Hi there,

you are responding pretty quickly, thanks for that but it seems like you are only processing "open" elements in your workflow as i didn't get a response to my question i've asked after my PR got closed, see https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/121#issuecomment-645821816.

So once again, perhaps my question is of interest for others too:

When will changes made to the repo be included in a new nuget package? What is your current nuget package release cycle?

Currently i'm working with a git submodule pointing to my fork of your repo but that's not ideal.

So lonG
Daniel

**Comment by leastprivilege** [comment]
pushed.

**Comment by ViRuSTriNiTy** [comment]
> pushed.

Freakin awesome, thanks! So i guess you don't have a release cycle according to your simple answer, you rather release by request, that's ok ;)

**Comment by leastprivilege** [comment]
I release when I have time ;)
