### ISSUE TITLE
Unable to get access token if multiple clients are configured where one of them is named "default"

### ISSUE THREAD

**Issue by rmja** [IdentityModel/IdentityModel.AspNetCore#126]
Hi,

I have a setup where I have configured two clients:

```
services
                .AddTransient<ITokenClientConfigurationService, CustomTokenClientConfigurationService>()
                .AddAccessTokenManagement(options =>
            {
                var defaultRequest = new ClientCredentialsTokenRequest();
                Configuration.GetSection("TokenClient").Bind(defaultRequest);
                defaultRequest.Scope = "somescope";

                options.Client.Clients.Add(TokenClientNames.Default, defaultRequest);

                var someOtherRequest = defaultRequest.Clone<ClientCredentialsTokenRequest>();
                someOtherRequest.Scope = "someotherscope";

                options.Client.Clients.Add(TokenClientNames.SomeOther, someOtherRequest);
            });
```

This fails because the following lines returns false, causing the configuration to be looked up by GetOpenIdConnectSettingsAsync() which in turn requires the ConfigurationManager to be defined on the OpenId options:
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/bbb95c58fa3087e87d1a22f559f7c3fbadbd173b/src/AccessTokenManagement/DefaultTokenClientConfigurationService.cs#L46

Could that line maybe instead be `if(_accessTokenManagementOptions.Client.Clients.TryGetValue(clientName, out requestDetails))` and then return the requestDetails if found in the dictionary?

**Comment by leastprivilege** [comment]
> This fails 

could you be a bit more specific?

**Comment by rmja** [comment]
In my case it fails because I do not have a ConfigurationManger on the OpenIdOptions, and so this line throws NullReferenceException:

https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/bbb95c58fa3087e87d1a22f559f7c3fbadbd173b/src/AccessTokenManagement/DefaultTokenClientConfigurationService.cs#L159

I guess the question is. What is the desired behavior when there are multiple configured clients and one of them is called "default". Should that _really_ change the behavior of the default client compared to the case when there is only one client?

**Comment by leastprivilege** [comment]
I am still not 100% clear what the problem is. but the behavior of the default config plumbing allows to have multiple **named** clients. If you don't pass a name explicitly, it falls bad to a "default" client. 

And that's IIRC either the one client (if it is only one) - or the OIDC-based configuration.

Do you think this behavior does not make sense? You are probably aware that you replace the config loading part if you want different behavior.

**Comment by rmja** [comment]
Ok I will try and clarify.

If I have _one_ defined, named client, no matter the name, then the associated request will always be returned from `GetClientCredentialsRequestAsync()`. For example:
```
options.Client.Clients.Add("default", defaultRequest)
```
or
```
options.Client.Clients.Add("some-other-name", defaultRequest)
```

If I have _multiple_ defined, named clients, then the name matters. For example:
```
options.Client.Clients.Add("client-A", requestA); // This returns the requestA from GetClientCredentialsRequestAsync
options.Client.Clients.Add("client-B", requestB); // This returns the requestB from GetClientCredentialsRequestAsync
```
_but_, if one of the clients is named exactly "default", then
```
options.Client.Clients.Add("default", requestA); // This does NOT return the requestA from GetClientCredentialsRequestAsync
options.Client.Clients.Add("some-other", requestB); // This returns the requestB from GetClientCredentialsRequestAsync
```

The behavior that makes sense to me would be that if a client is added with the explicit name "default" if more than one client is added, then that request should also be the one that is returned by `GetClientCredentialsRequestAsync()`.

Hope it makes sense :)

**Comment by leastprivilege** [comment]
And why don't you use the name in your application code when you have more than one client config?

**Comment by rmja** [comment]
I do. I just happened to explicitly use the name "default". After I renamed it to something else, the code started to work.

**Comment by leastprivilege** [comment]
Ah I see ;)
