### ISSUE TITLE
IdentityModel and Azure Functions V3 - Missing WebJobsAuthLevel authentication handler

### ISSUE THREAD

**Issue by lommez** [IdentityModel/IdentityModel.AspNetCore#131]
Hi, 
I've an Azure Function that doesnt need to be authenticated.
But after I registred the AddAccessTokenManagement and AddClientAccessTokenClient in the IoC, i got the following error:

![image](https://user-images.githubusercontent.com/10900667/87831520-1ac5bd80-c85a-11ea-9922-6ef1f77c192f.png)

Here is how i've implemented the function startup code:

![image](https://user-images.githubusercontent.com/10900667/87831625-6aa48480-c85a-11ea-96d8-76c25126d67e.png)

If i remove the piece of code, everything backs to works perfectly.

Is there something that i'm missing?

Thanks

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/110

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
