### ISSUE TITLE
What is the logic when the oauth2 does only return access_token but no refresh_token?

### ISSUE THREAD

**Issue by StefH** [IdentityModel/IdentityModel.AspNetCore#133]
When calling https://login.microsoftonline.com/{tenant-id}/oauth2/token, I get:
``` json
{
    "token_type": "Bearer",
    "expires_in": "3599",
    "ext_expires_in": "3599",
    "expires_on": "1595630297",
    "not_before": "1595626397",
    "resource": "https://xxx.azurewebsites.net",
    "access_token": "ey..."
}
```

And when I use the demo code from https://identitymodel.readthedocs.io/en/latest/aspnetcore/worker.html , all is working ok.

However, what will happen if 1 hour (> 3599 seconds) is passed, and I call the API again, will IdentityModel detect that a get or post to the API fails, and do a new call to aad to get a new access-token?

**Comment by leastprivilege** [comment]
For client credentials flow, a new access token will be requested once the old one is about to expire.

**Comment by StefH** [comment]
OK. Thanks.
