### ISSUE TITLE
Exception is thrown when no tokens are found

### ISSUE THREAD

**Issue by JohanPetersson** [IdentityModel/IdentityModel.AspNetCore#142]
I have multiple authentication schemes set up, one for OpenID Connect and then a custom one.

```
services
    .AddAuthentication(o => o.DefaultAuthenticateScheme = "customers-cookie")
    .AddCookie("customers-cookie", o =>
    {
        o.Cookie.Name = "login.customers";
    })
    .AddCookie("oidc-cookie", o =>
    {
        o.Cookie.Name = "login.admins";
    })
    .AddOpenIdConnect("oidc", o => o.SignInScheme = "oidc-cookie");

services.AddAccessTokenManagement();

services.AddClientAccessTokenClient("my-client");
```

The `customers` scheme is used by a custom sign-in handler.

When users are authenticated with the `oidc-cookie` scheme `my-client` works perfectly fine, a bearer token is appended to requests. The client also works when users are not authenticated, no bearer token is appended to requests. But when users are authenticated with the scheme `customers` an exception is thrown: `No tokens found in cookie properties. SaveTokens must be enabled for automatic token refresh.`. Which is true, there are no tokens in that cookie. 

Is it possible to configure so `my-client` still works but no bearer token is appended when users are authenticated but there are no tokens? I.e. work the same as when users are not authenticated at all, or why does the code assume that there must be tokens when users are authenticated https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/main/src/AccessTokenManagement/AuthenticationSessionUserTokenStore.cs#L46?

**Comment by leastprivilege** [comment]
The library is not designed for that scenario right now.

**Comment by JohanPetersson** [comment]
Would you accept a PR where we log a warning instead of throwing an exception when no tokens are present? Or would you like to add better support for this scenario?

**Comment by leastprivilege** [comment]
I will but that on back log for now. Need to think about it.

**Comment by leastprivilege** [comment]
I think this has changed a bit now. Have a look and feel free to re-open if still a problem.
