### ISSUE TITLE
cookie authentication security issue

### ISSUE THREAD

**Issue by Yogeshkad** [IdentityModel/IdentityModel.AspNetCore#143]
If i run the application which in this repository.

I created one user in the application

i login in application all works

i open different browser and open application url

and then in that browser if i copy past the old browser cookies
after that refresh 
user getting access to application without login by just copying the cookies of other user

**Comment by brockallen** [comment]
That's how cookies work.

**Comment by dewelloper** [comment]
If you dont want to use cokie dont use it. Use local storage etc

**Comment by Yogeshkad** [comment]
> If you dont want to use cokie dont use it. Use local storage etc

ok do you any reference link or example for asp.net core web app

**Comment by leastprivilege** [comment]
> If you dont want to use cokie dont use it. Use local storage etc

Which would result in the same behavior when copied to a different browser.

This discussion is not related to this library. closing.
