### ISSUE TITLE
CancellationToken not propagated all the way

### ISSUE THREAD

**Issue by cristiango** [IdentityModel/IdentityModel.AspNetCore#156]
In `ClientAccessTokenHandler` doesn't propagate the cancellation token to the underlining implementation that fetches the token from STS.
Problem is that `SetTokenAsync` doesn't take cancellationToken
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/4e700baa094b0a7e26836981b3395d933ab1b474/src/AccessTokenManagement/ClientAccessTokenHandler.cs#L31-L34

More than happy to send a PR

**Comment by leastprivilege** [comment]
go for it!
