### ISSUE TITLE
Custom grant_type

### ISSUE THREAD

**Issue by k-u-s** [IdentityModel/IdentityModel.AspNetCore#163]
If  during registartation in DI user sets GrantType to custom value like:

                options.Client.Clients.Add(TokenClientName, new ClientCredentialsTokenRequest
                {
                     Address = "https://demo.identityserver.io/connect/token",
                     ClientId = "m2m.short",
                     ClientSecret = "secret",
                     Scope = "api" // optional
                     GrantType = "custom_grant",
                });

and uses extension method AddClientAccessTokenHandler GrantType is overwritten by client_credentials value.

https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/b6b14b946295635d472eb8c5447fa444662e43f6/src/AccessTokenManagement/TokenEndpointService.cs#L45

if in line above would be used extension method RequestTokenAsync instead of RequestClientCredentialsTokenAsync value set by user is preserved.

Is such behaviour be design?

> As workaround it is possible to change implementation of ITokenEndpointService to copy of TokenEndpointService 
> and replace line mentioned above with something like
> 
>            var grantType = string.IsNullOrEmpty(requestDetails.GrantType)
>                ? OidcConstants.GrantTypes.ClientCredentials
>                : requestDetails.GrantType;
>
>            return grantType == OidcConstants.GrantTypes.ClientCredentials
>                ? await _httpClient.RequestClientCredentialsTokenAsync(requestDetails, cancellationToken: cancellationToken)
>                : await _httpClient.RequestTokenAsync(requestDetails, cancellationToken: cancellationToken);

**Comment by leastprivilege** [comment]
tbh - it was never designed for custom grant types. But I don't see a reason why it shouldn't.

**Comment by leastprivilege** [comment]
I looked at your proposed code - it feels a bit hacky ;) e.g. you would lose the Scope parameter when simply downcasting.

I will leave this open to think about it.

**Comment by k-u-s** [comment]
It is, I did not spend much time thinking about it. Just wanted to adjusted it to current scenerio. 

From what i understand when using custom grand, scope param should be missing. At least in my case it should be missing but I did not check it against official spec. And I am integrating with provider that I think is not following to strictly official spec so it is not probably the best example.

**Comment by leastprivilege** [comment]
I am not planning to add support for custom grant types right now. Feel free to fork and make it work for you.
