### ISSUE TITLE
Multi-tenancy considerations

### ISSUE THREAD

**Issue by natelaff** [IdentityModel/IdentityModel.AspNetCore#166]
Trying to think through how to implement my scenario and wanted to get some feedback before even attempting a PR

My IS4 instance is multitenant enabled via endpoint routing with tenant name in the path.

I have an Azure Function that needs to get a client_credentials token with a dynamic tenant. It's processing messages with a tenant name and needs to get the appropriate credentials.

So, right out of the gate, I can't use the DefaultTokenClientConfigurationService. Easy enough. But the issue remains I need to somehow have the context of which tenant I am connecting to.

I think if args were added to ITokenClientConfigurationService.GetClientCredentialsRequestAsync to pass in additional context that would solve my immediate need? Is that something that would be approved?

I could just parse out tenant names by passing it in with the client name, i.e. {tenantName}_{clientName} then split those in the custom ITokenClientConfigurationService, but I could see the need for wanting more stuff in a dynamic configuration like this.

In my instance for UserAccessTokens I can retrieve the multi tenant context via HttpContext, so that is covered, it's just client credentials that I need to address at the moment.

Anyways, looking for feedback :)

**Comment by natelaff** [comment]
This would also need to flow to the ClientAccessTokenHandler (which is really where I think I'd be hitting it for my purpose, I think I would just use HttpClientFactory.Create and add that handler in directly with a tenant name in this Azure function)

**Comment by leastprivilege** [comment]
Hey, 

sorry. I don't really have the time right now to think though all these implications. Can't you for now try to make it work with passing your context along using HttpContext.Items?

**Comment by natelaff** [comment]
No worries. Unfortunately regarding your suggestion there is no HttpContext in Azure functions app where I'm trying to use this :) I'll keep thinking through it but will be interested on your feedback once you have some time.

Seems like a good scenario to hit for even just passing acr_values tenant since that is obviously dynamic, but it's your library and I don't want to step on toes by trying to force anything in, especially if it could be done better.

**Comment by natelaff** [comment]
Didn't find a solid solution. Will wait for further guidance on this for how you think this should be addressed.

**Comment by leastprivilege** [comment]
So what are you proposing?

**Comment by natelaff** [comment]
@leastprivilege well there should be a way to pass parameters in the request. Think of acr_values tenant. What would be a clean way to have that moved through the flow?

**Comment by leastprivilege** [comment]
something like

```cs
public static async Task<string> GetClientAccessTokenAsync(
    this HttpContext context, 
    string clientName = AccessTokenManagementDefaults.DefaultTokenClientName, 
    object context = null,
    bool forceRenewal = false,
    CancellationToken cancellationToken = default)
{
    var service = context.RequestServices.GetRequiredService<IAccessTokenManagementService>();

    return await service.GetClientAccessTokenAsync(clientName, context, forceRenewal, cancellationToken);
}
```

???

And that context would be available all the way through?

**Comment by natelaff** [comment]
That's kind of what I was thinking -- I didn't know if strongly typing acr values made sense (I don't use acr tenant personally, but could obviously piggy back off of it)

Then if you had to deal with caching considerations for the context was a question I think I ran into. It's been over a month since I ran through these scenarios and tried to modify code to tackle this problem but didn't want to go too deep without your input.

**Comment by leastprivilege** [comment]
OK - well tbh - I don't know either. Since this is not my problem, I don't really know the solution ;)

Feel free to clone it, and use the code directly and modify it to your needs.

**Comment by natelaff** [comment]
Would you accept PR using the object context?

**Comment by leastprivilege** [comment]
no - this feels like a hack for a niche scenario.

Just make it work for you - and if it is a proven approach we can think about back-porting it.

**Comment by natelaff** [comment]
Yes, after experimenting this way feels hacky... however I disagree with niche scenario. IS4 supports accepting tenant in acr_values-- I think this lib should support sending it ;)

**Comment by leastprivilege** [comment]
hm - I personally never used acr_values for client creds. Is this how you are using it?

**Comment by natelaff** [comment]
That's essentially the goal yes :) M2M needs to be tenant aware, too :)

**Comment by leastprivilege** [comment]
OK - I think while doing some re-work I can add a general "context" object to flow through...

**Comment by natelaff** [comment]
Great! I think that will be a great addition to the library.

**Comment by leastprivilege** [comment]
Please give 4.0.0-preview.2 a try and let me know if this works for you.

**Comment by natelaff** [comment]
Thanks, I have pulled it down and am trying to wrap my head around the refactoring that took place and how to wire this up now. I had a pretty clear idea in my head back in December, but now I'm struggling to see my path.

**Comment by leastprivilege** [comment]
See the signature of the GetClientAccessToken HttpContext extension.

**Comment by VictorioBerra** [comment]
@leastprivilege FYI there are 0 references to this method, it is unused https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/main/src/AccessTokenManagement/TokenManagementHttpContextExtensions.cs#L39

**Comment by VictorioBerra** [comment]
Which is probably expected.

Anyways, I think the confusion here is how to use the context, not how to set it. If you set the ProtocolMessage `Properties` property I notice it actually is serialized and sent https://github.com/IdentityModel/IdentityModel/blob/main/src/Client/Messages/ProtocolRequest.cs#L189

But if you set Options in .NET 5, this is not the case.

**Comment by leastprivilege** [comment]
> See the signature of the GetClientAccessToken HttpContext extension. 

Or for your use case the methods on IClientAccessTokenManagementService

**Comment by leastprivilege** [comment]
@natelaff Any feedback. Otherwise I have to assume you are happy ;)

**Comment by natelaff** [comment]
I got stuck and missed your comment about IClientAccessTokenManagementService. I will try using that today and see where I get!

**Comment by natelaff** [comment]
It seems as though it's caching the token based on client name which is throwing off my current test. Consider this...

My IdentityServer instance uses tenant name in the path, so https://myidentityserver/{tenantName}/connect/token

I have an ASP.NET Core website that works great with UserAccessTokens (because I override OpenIdConnectOptions in an IOptionsMonitor to get the authority.) So users log in and it's switching access tokens perfectly in this scenario.

Now, also in this ASP.NET Core website, I have an area with public access that must use client credentials to connect.

I add a new ClientConfigurationService which will replace the address having {tenantName} with the current tenant context.

```
            services.AddTransient<ITokenClientConfigurationService, TenantAwareTokenClientConfigurationService>();
            services.AddAccessTokenManagement(options =>
            {
                options.Client.Clients.Add("webpublic", new ClientCredentialsTokenRequest
                {
                    Address = "https://myidentityserver/{tenantName}/connect/token",
                    ClientId = "public",
                    ClientSecret = "<snip>",
                    Scope = "api"
                });
            });
             
           // ... a bunch of other stuff

            services.AddHttpClient("webpublichttp", ConfigureApiClient) // nevermind this func, it just sets the address
            .AddClientAccessTokenHandler("webpublic");
```



https://mywebsite/{tenantName}/dashboard (user access token, working great)



https://mywebsite/{tenantName}/public

When I hit this I spin up a new HttpClient from Factory and throw that into a Refit API client.

```
    public class PublicController : Controller
    {        
        private readonly ISomeClient _someClient;
        public PublicController(IHttpClientFactory clientFactory, IClientAccessTokenManagementService clientAccessTokenManagementService, TenantInfo tenantInfo)
        {            
            HttpClient publicHttpClient = clientFactory.CreateClient("webpublichttp");            
            _someClient = RestService.For<ISomeClient>(publicClient);
        }
```

This works great... once. After that if the tenant is switched it's using the same access token that's cached.

**Comment by natelaff** [comment]
For the record, even without the IS using tenant name in the path, this will still be an issue here since the cache is not able to take context in any way.

For a one and done Functions app, this will probably work fine. I will try that next.

**Comment by leastprivilege** [comment]
OK - I'll have a look

**Comment by natelaff** [comment]
I think if you used IOptions<AccessTokenManagementOptions> in ClientAccessTokenCache (and probably elsewhere just for good measure), people with this requirement could work through this. You can modify the cache key to include a tenant name for the request and I think that will square this away!

**Comment by natelaff** [comment]
Yeah that would work too. I think IOptionsMonitor in the cache service would also be appreciated for these scenarios. Actually, if I had that, I think the entire context object you added would be moot in a web app with this requirement (still necessary for functions app I think), because at least for me, I can hit everything I need with changing that cache key per request and a custom TokenClientConfigurationService. It was the cache that was messing with me the entire time it seems.

```
    public class CloudAppTokenClientConfigurationService : DefaultTokenClientConfigurationService
    {
        private readonly TenantInfo _tenantInfo;
        public CloudAppTokenClientConfigurationService(TenantInfo tenantInfo, IOptions<AccessTokenManagementOptions> accessTokenManagementOptions, IOptionsMonitor<OpenIdConnectOptions> oidcOptions, IAuthenticationSchemeProvider schemeProvider, ILogger<DefaultTokenClientConfigurationService> logger) : base(accessTokenManagementOptions, oidcOptions, schemeProvider, logger)
        {
            _tenantInfo = tenantInfo;
        }

        public async override Task<ClientCredentialsTokenRequest> GetClientCredentialsRequestAsync(string clientName, ClientAccessTokenParameters parameters)
        {
            var result = await base.GetClientCredentialsRequestAsync(clientName, parameters);
            result.Address = result.Address.Replace("{TenantName}", _tenantInfo.Name);
            return result;
        }
    }
```

**Comment by leastprivilege** [comment]
does that work for you?

**Comment by natelaff** [comment]
@leastprivilege yes, the GenerateCacheKey method to override there is a good addition. If you also changed that IOptions scope  there are multiple options to be as flexible as needed.

With that, I could just change some middleware I use and that's the only thing that would be needed for this instance.

```
                .WithPerTenantOptions<AccessTokenManagementOptions>((options, tenantInfo) =>{
                    options.Client.CacheKeyPrefix += $"{tenantInfo.Name}:";
                })
```

Thanks for these changes. I think it covers some good bases!

**Comment by leastprivilege** [comment]
> if you also changed that IOptions scope there are multiple options to be as flexible as needed.

don't follow - what should I change?

**Comment by leastprivilege** [comment]
..and why?

**Comment by natelaff** [comment]
Changing AccessTokenManagementOptions.Client.CacheKeyPrefix per request to include the tenant name in my case, (or any other piece of information the dev needs), will allow this service to use this cache key dynamically.

I could see situations where a dev has a client per tenant -- this would allow for that type of scenario as well I would think.

**Comment by leastprivilege** [comment]
Well - I might be wrong, but IOptions is not really meant to do per-request mutation of options....at least I never saw it like this.

I'd rather derive from the configuration service base class and resolve the tenant name there somehow.

**Comment by natelaff** [comment]
Actually the way it's done on my end should be able to even deal with replacing IOptions interfaces as well, unless you're caching that options value somewhere. So I'm not sure why it's not. I will peruse your code more.

**Comment by leastprivilege** [comment]
> This is what the ASP.NET Core OIDC middleware uses.

How are they using it to do per-request options mutation?

From my POV, I am done. Does the code have the customizability to implement what you need. It does exactly what you asked for - being able to pass a contextual object through the whole call chain.

**Comment by natelaff** [comment]
Well if you want to push a preview package I'll give it a try :) Looks like everything should be great though.

**Comment by natelaff** [comment]
Hmm. For some reason it continues to keep pulling the same access token despite the tenant switch. Will try and pull code and debug soon.

**Comment by natelaff** [comment]
Ok, so what appears to be happening, is once the client request is set, it doesn't reload from config...

`
            services.AddAccessTokenManagement(options =>
            {
                options.Client.Clients.Add("webpublic", new ClientCredentialsTokenRequest
                {
                    Address = "https://myidentityserver/{tenantName}/connect/token",
                    ClientId = "public",
                    ClientSecret = "<snip>",
                    Scope = "api"
                });
            });
`

then

`
    public class TenantTokenClientConfigurationService : DefaultTokenClientConfigurationService
    {
        private readonly TenantInfo _tenantInfo;
        public TenantTokenClientConfigurationService(TenantInfo tenantInfo, IOptions<AccessTokenManagementOptions> accessTokenManagementOptions, IOptionsMonitor<OpenIdConnectOptions> oidcOptions, IAuthenticationSchemeProvider schemeProvider, ILogger<DefaultTokenClientConfigurationService> logger) : base(accessTokenManagementOptions, oidcOptions, schemeProvider, logger)
        {
            _tenantInfo = tenantInfo;
        }

        public async override Task<ClientCredentialsTokenRequest> GetClientCredentialsRequestAsync(string clientName, ClientAccessTokenParameters parameters)
        {
            var result = await base.GetClientCredentialsRequestAsync(clientName, parameters);
            result.Address = result.Address.Replace("{TenantName}", _tenantInfo.Name);
            return result;
        }
    }
`

Once result.Address is replaced, it never let's that go. It persists to the clients collection that way, which is why my tenant never switches.

Trying to figure out why this happens. Haven't got there yet.

**Comment by leastprivilege** [comment]
last call...

**Comment by natelaff** [comment]
It seems to work, there is some goofiness with it that I mentioned above, but it's functional.

**Comment by leastprivilege** [comment]
OK. Cool. Will release a new version then soon.
