### ISSUE TITLE
AddAccessTokenManagement: Only client_credentials grant type is supported?

### ISSUE THREAD

**Issue by bugproof** [IdentityModel/IdentityModel.AspNetCore#171]
I wanted to use device flow or authorization code flow with automatic refresh token management is it possible with this library?

I looked at the code and it seems like this is the case and there's no way you can configure it. IdentityModel helper has required HttpClient extensions though.

**Comment by leastprivilege** [comment]
see here for code flow...

https://identitymodel.readthedocs.io/en/latest/aspnetcore/web.html

**Comment by bugproof** [comment]
@leastprivilege what if an API uses only OAuth 2.0 without OID? Will this work?

**Comment by leastprivilege** [comment]
no

**Comment by bugproof** [comment]
okay, thank you. I guess I will have to come with my own solution then
