### ISSUE TITLE
grant_type

### ISSUE THREAD

**Issue by Sendell** [IdentityModel/IdentityModel.AspNetCore#172]
Besides the open issue/feature request for custom grant_types, I was wondering how to add support for grant_type "password". Which is within the OAuth specification as far as I can tell (I'm not at all an expert)

Looking through the source I think I can see it being partially supported by the IdentityModel project. But I'm not capable of implementing this quickly.

And if I set the GrantType manually it gets overwritten in 
HttpClientTokenRequestExtensions.RequestClientCredentialsTokenAsync

As I currently only need to change that, I was wondering if there is a quick way to override that behaviour.

**Comment by leastprivilege** [comment]
Password is not recommended nor supported.

This library focuses on 2 use cases: interactive web apps with code flow and machine to machine communication with client credential flow.
