### ISSUE TITLE
Can IdentityModel help retrieve/refresh user tokens that are saved in database for offline background tasks?

### ISSUE THREAD

**Issue by felinepc** [IdentityModel/IdentityModel.AspNetCore#180]
My ```IdentityServer``` uses external authentication via Microsoft/Google etc. During the authentication flow, I save the tokens (including access tokens and refresh tokens) issued by these external IDPs into the database, using the integrated ASP.Net Core Identity (inside the ```AspNetUserTokens``` table).

As you know, after ```IdentityServer``` authenticates a user via external IDP, the external temp cookie is deleted, so there is no more context or auth result of those to refer to.

Now I need to use these saved external tokens to call Microsoft/Google's APIs in the background on behalf of the users. The access tokens will need to be refreshed using the stored refresh tokens.

My understanding is that ```IdentityModel.AspNetCore``` can handle user token caching/refreshing when given a ```HttpContext``` to work with. But in this case the context is not available, rather the tokens are all saved in database. 

I'm looking over the documentation and can't seem to figure out if there's a way to use or extend ```IdentityModel``` for my scenario. If not I'll just have to write my own ```HttpClient``` handlers etc. But just want to make sure before I do that to avoid reinventing the wheel.

Thanks!

**Comment by leastprivilege** [comment]
This was not the focus when I built this library. So feel free to re-use the relevant parts to create something that works for you.

**Comment by VictorioBerra** [comment]
@felinepc Your situation is so custom, id create your own handler and use a popular cache library.

But, if you look at the actual code and not the docs you begin to see how simple this library is and the parts you would beed to replace to achieve your goal. Look at `IClientAccessTokenCache` and `IUserTokenStore` swapping things in the library are really easy.
