### ISSUE TITLE
Requesting a token using the authorization_code Grant Type does not work

### ISSUE THREAD

**Issue by ccaneke** [IdentityModel/IdentityModel.AspNetCore#200]
I am getting an Unauthorized error when I make a request to a token endpoint using IdentityModel's request methods. I believe the API I am trying to get a token from uses OAuth2. 

I wanted to use IdentityModel to get an access token because it needs less code. The regular way of using basic authentication with the dotnet HttpClient successfully retrieves a token from the token endpoint. 

My code is like this:

```
var response = await HttpClientTokenRequestExtensions.RequestAuthorizationCodeTokenAsync(_client, new AuthorizationCodeTokenRequest
{
    Address = "https://www.example.com/api/access_token/",

    ClientId = "client",
    ClientSecret = "secret",

    Code = code,
    RedirectUri = "https://app.com/callback"
});
```

**Comment by VictorioBerra** [comment]
Is `IdentityServerPipeline.TokenEndpoint` your actual token endpoint?

**Comment by ccaneke** [comment]
@VictorioBerra No, that was a mistake. My endpoint is something like `https://www.example.com/api/access_token/`

**Comment by leastprivilege** [comment]
a) this is the wrong repo (use IdentityModel instead)
b) this is of course not enough information to diagnose the problem

Please re-open in IdentityModel with network traces, server logs or similar.
