### ISSUE TITLE
Possibility to split the library so client token management doesn't depend on ASP.NET Core shared framework

### ISSUE THREAD

**Issue by mderriey-prospa** [IdentityModel/IdentityModel.AspNetCore#212]
Hey 👋

Thanks for the awesome library, it's such a time-saver 🙇‍♂️

We'd love to use it in our web apps as well as our daemon apps to facilitate our service-to-service communications.

Our company has a policy where worker apps should be based on the .NET runtime Docker images, which don't include the ASP.NET shared framework.
As a result, at this stage we can't use it as-is.

We were wondering if you'd be open to the idea to split the library so part of it doesn't depend on the ASP.NET Core shared framework.

I understand it's not clear-cut; while I initially thought that we could potentially separate the user and client token management features, I then realised that the client token management has a feature to piggyback on the ASP.NET Core authentication system to get the OIDC settings from the default challenge authN scheme.

Please let me know what your thoughts around this are, and again thank you for taking the time to create this 💯

Cheers.

**Comment by leastprivilege** [comment]
Hey, 

long time no speak!

My initial reaction is "no" ;)

This sounds like more engineering work and maintenance and just more complexity in general just to satisfy a "niche requirement" - e.g. it probably means maintaining 2 Nugets instead of one, splitting extension methods etc. - right?

That being said - I am happy to listen to your more detailed "attack plan" how you would solve the problem. But I cannot promise that I will agree.

**Comment by mderriey-prospa** [comment]
> long time no speak!

It's been a while, yes 😄 

> This sounds like more engineering work and maintenance and just more complexity in general just to satisfy a "niche requirement" - e.g. it probably means maintaining 2 Nugets instead of one, splitting extension methods etc. - right?

Agreed.

> That being said - I am happy to listen to your more detailed "attack plan" how you would solve the problem. But I cannot promise that I will agree.

I don't have one as I wanted to get your initial feeling first.

It's not "just" splitting the user and client token management features into 2 NuGet packages, since the client token feature relies on `IAuthenticationSchemeProvider` if the client options don't specify an explicit OIDC scheme name.

<https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/27e966bf6729530e4a7480478f18302fe996a7f6/src/AccessTokenManagement/DefaultTokenClientConfigurationService.cs#L159-L173>

So to satisfy our requirements, it could end up being 3 packages:

- The user token management.
- The client token management with support to hook into the authN system (because people might be interested in this).
- The client token management without support to source OIDC settings from the authN system, but support for the consumer to specify the name of the OIDC scheme if required (since that only depends on a specific NuGet package).

In our case, we'd only be interested in the third one, given most of the projects we'd use this are APIs (hence no OIDC provider) and we configure the clients fully (token endpoint, client id, client secret).

As you said, it seems like a lot of extra work for an edge case.

We'll probably start maintaining a fork where we strip all the ASP.NET-dependent bits.

Thanks for getting back to me so quickly, much appreciated, and thanks again for the killer library!

**Comment by leastprivilege** [comment]
Thanks!

Sounds reasonable.

Take care!
