### ISSUE TITLE
Microsoft.AspNetCore.Authentication.OpenIdConnect vs IdentityModel

### ISSUE THREAD

**Issue by MoishyS** [IdentityModel/IdentityModel.AspNetCore#213]
Hi,

I am looking into setting up an OIDC client (with IS4), do I need IdentityModel for this? or is [Microsoft.AspNetCore.Authentication.OpenIdConnect](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect) enough?
in general, what is the difference between these two?

**Comment by VictorioBerra** [comment]
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/main/src/IdentityModel.AspNetCore.csproj#L26

**Comment by MoishyS** [comment]
ok, so I see it's using the Microsoft OpenIdConnect. but I still don't understand what IdentityModel.AspNetCore does.
if I want to set up an OIDC client in asp.net core, do I need IdentityModel.AspNetCore? does it help in any way? the readme is a bit vague.
(there are online tutorials to do it with IdentityModel, and others that just use Microsoft.AspNetCore.Authentication.OpenIdConnect. that's why i am asking)

Thanks

**Comment by brockallen** [comment]
IdentityModel.AspNetCore adds token renewal and management features for the tokens obtained via Microsoft OpenIdConnect. They don't include that in their library.

**Comment by MoishyS** [comment]
got it, thanks for your time
