### ISSUE TITLE
Cookie size growing when using claims transformer on access token update.

### ISSUE THREAD

**Issue by MichaelJRogersGM** [IdentityModel/IdentityModel.AspNetCore#214]
We're using this library along with an implementation of IClaimsTransformation adding claims from an outside system.  

When the access token is expired and is refreshed it is then storing all the claims that were added by the claims transformer to the cookie when SignInAsync is called.  

Do you have any suggestions on how to avoid this behavior?  We are trying to avoid implementing a TicketStore and have the potential to have more claims than we would want to store in a cookie.    We were hoping that we could keep it just the basic principle and tokens in the cookie.

```c#
  public class AuthenticationSessionUserAccessTokenStore : IUserAccessTokenStore
    {
      ...
      public async Task StoreTokenAsync(ClaimsPrincipal user, string accessToken, DateTimeOffset expiration,
                  string refreshToken = null, UserAccessTokenParameters parameters = null)
      {
         ...
  
         await _contextAccessor.HttpContext.SignInAsync(parameters.SignInScheme, result.Principal, result.Properties);
    
       }
       ....
}
```

This closed issue may be related.
https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/174

Thanks
Michael

**Comment by brockallen** [comment]
What does your claims transformer look like?

https://brockallen.com/2017/08/30/beware-in-asp-net-core-2-0-claims-transformation-might-run-multiple-times/

**Comment by MichaelJRogersGM** [comment]
Thanks for the response.  We're following that pattern creating a new claims principal from the result of the transformer.  Everything works as expected until the access token expires and is updated in the cookie pushing the transformed claims into the principal.  Then the next time around the claims are already there from the transformer.

```c#
public async Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
        {
            if (principal == null || principal.Identity == null || string.IsNullOrEmpty(principal.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value))
            {
                return principal;
            }

            var identity = (ClaimsIdentity)principal.Identity;

            var claimsIdentity = new ClaimsIdentity(identity.Claims, identity.AuthenticationType, identity.NameClaimType, identity.RoleClaimType);

            var userGuid = principal.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value;

            List<Claim> claims = memoryCache.Get<List<Claim>>(userGuid);

            if (cacheTime == null || claims == null)
            {
                var userRoles = // load roles/claims from external source
                var userClaims = userRoles.SelectMany(ur => ur.RoleClaims);

                claims = userClaims.Select(claim => CreateClaim(claim))
                    .Union(userRoles.Select(role => CreateClaim(role)))
                    .ToList();

                if (cacheTime != null)
                {
                    memoryCache.Set(userGuid, claims, TimeSpan.FromMinutes((int)cacheTime));
                }
            }

            claimsIdentity.AddClaims(claims);

            return await Task.FromResult(new ClaimsPrincipal(claimsIdentity));
        }
```

Thanks
Michael

**Comment by brockallen** [comment]
Right... so then later on there's plumbing that re-issues the cookie with the current claims that are in the principal. It would not know about the semantics of the claims transformer. 

So do you have a suggestion or proposal for how to avoid this?

**Comment by MichaelJRogersGM** [comment]
Is there a way to only update the properties that store the access token?  I've not been able to find anything.

The only other option I can think of is adding a property to the claims added by the transformer so that they can be identified and removed before storing the principal.

**Comment by brockallen** [comment]
Ok... well, @leastprivilege is out on holiday so once he's back we'll see what we can think of.

**Comment by MichaelJRogersGM** [comment]
Sounds good, thanks for your help.  Let me know if you need any other info or help with a change.

Michael

**Comment by leastprivilege** [comment]
I will have a look

**Comment by leastprivilege** [comment]
OK - I see the problem - 

`await _contextAccessor.HttpContext.AuthenticateAsync(parameters.SignInScheme);`

returns the transformed principal.

I could offer a virtual on the session store that you can implement to filter the claims before re-issuing the cookie. Would that help?

**Comment by leastprivilege** [comment]
Something like

https://github.com/IdentityModel/IdentityModel.AspNetCore/pull/219/commits/c37f9b7fd7eed431e9dda8ec9268cf0a8236247c

**Comment by MichaelJRogersGM** [comment]
That looks good, I think that will work for what we need thanks!

Michael

**Comment by leastprivilege** [comment]
OK will merge it.
