### ISSUE TITLE
IdentityModel.Extensions.HttpClient

### ISSUE THREAD

**Issue by prochnowc** [IdentityModel/IdentityModel.AspNetCore#237]
Hi,

would it be possible to split the library where the ClientAccessToken part does not have a dependency on AspNetCore ?

I have several "worker" services which do require client credentials authentication, so far these services do only depend on Microsoft.Extensions. As far as I can see,  the ClientAccessTokenHandler does not depend on AspNetCore.

Thanks.

**Comment by leastprivilege** [comment]
I can see that this is more convenient for you!

But this is not really a scenario I care about and would result in extra maintenance work. Feel free to fork the code to optimize it for your scenario.

**Comment by prochnowc** [comment]
Do you accept PRs for such refactoring? Or do I need to fork it and continue on my own ?
Thanks for the answer.

**Comment by leastprivilege** [comment]
Feel free to fork it!
