### ISSUE TITLE
AddClientAccessTokenClient not found

### ISSUE THREAD

**Issue by dthemg** [IdentityModel/IdentityModel.AspNetCore#240]
Hi 

I can't seem to find the `AddClientAccessTokenClient` function when using IdentityModel - see for example use [here](https://identitymodel.readthedocs.io/en/latest/aspnetcore/worker.html) or [here](https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/110). To me, I just get a that there is no such definition for `IServiceCollection`. I MUST be missing something obvious here:

Using:
`IdentityModel` v5.2.0
`IdentityModel.AspNetCore` v4.0.1

Here is my usage:
```
...
using IdentityModel.Client;
using IdentityServer4.Models;
...

services.AddClientAccessTokenManagement(options =>
{
    options.Clients.Add("identityserver", new ClientCredentialsTokenRequest
    {
        Address = clientAuthenticationOptions.AuthenticationHost,
        ClientId = clientId,
        ClientSecret = clientSecret.Sha256(),
        Scope = "api1"
    });
});

// AddClientAccessTokenClient is not recognized
services.AddClientAccessTokenClient("client", "identityserver", configureClient: client =>
{
    client.BaseAddress = new Uri(clientAuthenticationOptions.AuthenticationHost);
}); 
```

**Comment by brockallen** [comment]
`AddClientAccessTokenHttpClient` and `AddUserAccessTokenHttpClient`?

**Comment by leastprivilege** [comment]
yes
