### ISSUE TITLE
Calling GetUserAccessTokenAsync() twice when token renews causes two renewals

### ISSUE THREAD

**Issue by brockallen** [IdentityModel/IdentityModel.AspNetCore#241]
When I call HttpContext.GetUserAccessTokenAsync() and it causes token renewal, and then I call it again (e.g. on the next line of code in the same HTTP request) it will re-trigger token renewal because internally it's getting the cached AuthResult from the cookie handler with the old expiration, and thus it re-triggers renewal.

Perhaps we can/should do some caching of some sort internally (e.g. scoped service in DI?).

**Comment by leastprivilege** [comment]
Let's discuss this
