### ISSUE TITLE
Consider sliding the cookie after token renewal

### ISSUE THREAD

**Issue by brockallen** [IdentityModel/IdentityModel.AspNetCore#242]
Given that when the token is renewed and the cookie re-issued, the cookie sliding logic is eclipsed, then there are edge cases when the user is active but the cookie gets expired. 

We can consider allowing the cookie to slide when we re-issue the cookie if the cookie was originally marked as sliding. By setting the `Properties.ExpiresUtc` to `null`, internally the cookie handler will set the new expiration. And we only do this if the cookie allow refresh, by checking `Properties.AllowRefresh`. 

For example in `AuthenticationSessionUserAccessTokenStore.StoreTokenAsync`:

```
            if (result.Properties.AllowRefresh == true)
            {
                result.Properties.ExpiresUtc = null;
            }

            await _contextAccessor.HttpContext.SignInAsync(parameters.SignInScheme, transformedPrincipal, result.Properties);
```

Didn't test this code, but I think that's all it would take.

**Comment by leastprivilege** [comment]
This is done, right?
