### ISSUE TITLE
Support extension grants for user tokens

### ISSUE THREAD

**Issue by grapereader** [IdentityModel/IdentityModel.AspNetCore#243]
As far as I can tell, it is not possible to request additional scopes for an intermediate user access token.

Referring to the scenario in this documentation: https://identityserver4.readthedocs.io/en/latest/topics/extension_grants.html#example-simple-delegation-using-an-extension-grant

It is possible using IdentityModel directly (from the above docs):
```
return await client.RequestTokenAsync(new TokenRequest
    {
        Address = disco.TokenEndpoint,
        GrantType = "delegation",

        ClientId = "api1.client",
        ClientSecret = "secret",

        Parameters =
        {
            { "scope", "api2" },
            { "token", userToken}
        }
    });
```

**Comment by leastprivilege** [comment]
I am not following. Do you mean if this is possible with `IdentityModel` or `IdentityModel.AspNetCore`. 

For the latter - no.

**Comment by grapereader** [comment]
Yes, I meant for AspNetCore.

This library manages token lifetimes for worker services, so not much of a stretch to hope it would manage delegated tokens as well. The problem domains are similar: store delegated tokens, request new ones when expired, add them to http client requests.

Would this ever be on the roadmap at some point?

**Comment by leastprivilege** [comment]
I have no plans on adding it myself - or the complexity that comes with it.
