### ISSUE TITLE
Question: Motivation switching from IOptions<T> to T

### ISSUE THREAD

**Issue by prochnowc** [IdentityModel/IdentityModel.AspNetCore#248]
May I ask what was the motivation behind switching from e.g. `IOptions<AccessTokenManagementOptions>` (v3) to `AccessTokenManagementOptions`  (v4) ?

With `IOptions<T>` it was possible to transparently register several clients in different unrelated parts of my application (e.g. plugins).
Now I need a single point where all clients are configured at once, making it impossible to have each plugin calling `AddAccessTokenManagement()` with it's own client configuration.

Sure I could introduce my own options type which is registered together with access token management by the host application, but with v3 it was much easier.

Thanks for the answer.

**Comment by leastprivilege** [comment]
No particular motivation - can't remember tbh
