### ISSUE TITLE
Blazor server sample request

### ISSUE THREAD

**Issue by rasaconsulting-sandy** [IdentityModel/IdentityModel.AspNetCore#252]
Can a Blazor server example please (i.e. not a WASM) be added to remove the confusion on how the application would automatically redirect to the login page of the IdentityServer site.  

Please refer to previous discussions which states that BFF shouldn't be used for Blazor Server applications and to follow the MVC sample (which isn't 100% transferable): https://github.com/DuendeSoftware/IdentityServer/discussions/623

Thank-you for considering.

**Comment by leastprivilege** [comment]
Will put on my todo list. 

If you use the Blazor Server template with Azure AD authN, it should contain the relevant code, though.

**Comment by rasaconsulting-sandy** [comment]
Thanks!  I'm not using the Azure AD authN - this was [geroeinimo](https://github.com/geroeinimo).  I'm trying to use it with the AspNetCore Identity scaffold provided by Microsoft.

**Comment by leastprivilege** [comment]
Sure - but that is via OpenID Connect - just like AAD.

**Comment by rasaconsulting-sandy** [comment]
OK cool - I'm still struggling with the bit that automatically redirects the user from the Blazor server client to the IdentityServer login page.  The rest appears to be working well.  

I'm playing around with different scenarios to try and get this to work still.

**Comment by joecuevasjr** [comment]
> If you use the Blazor Server template with Azure AD authN, it should contain the relevant code, though.

@leastprivilege Is this the Visual Studio 2022 Blazor Server template? If not, do you have a resource that shows the code you're describing? I'd appreciate it. Thanks!

**Comment by leastprivilege** [comment]
OK - I started working on a sample. It's here:
https://github.com/IdentityModel/IdentityModel.AspNetCore/tree/main/samples/BlazorServer

**Comment by rasaconsulting-sandy** [comment]
Awesome - thanks!  I’ll have a look now.

**Comment by rasaconsulting-sandy** [comment]
I've got this working now.  Thanks so much for doing this sample - I really appreciate it!!!
