### ISSUE TITLE
Question: Breaking change to method signature

### ISSUE THREAD

**Issue by joarkm1** [IdentityModel/IdentityModel.AspNetCore#254]
How do I overcome this change? The method `IClientAccessTokenCache.GetAsync` and `SetAsync` now require a parameter `ClientAccessTokenParameters parameters`.

The change is introduced in commit 88b63ec4fa0478b7edd46c6249741ab81e490fb5 (in 4.0.0-preview.3).

Can it be set to null?

**Comment by VictorioBerra** [comment]
You could clone the project and see for yourself, its pretty small.

But yes, you can pass null: https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/main/src/AccessTokenManagement/ClientAccessToken/ClientAccessTokenCache.cs#L108

**Comment by joarkm1** [comment]
Thank you. I did, just wanted a second opinion. But if it can be set to null, couldn't it be optional? It is only used in the method `GenerateCacheKey`, it seems like ;-)
