### ISSUE TITLE
Authorization not being added to HttpClient - with client credentials

### ISSUE THREAD

**Issue by mahgo** [IdentityModel/IdentityModel.AspNetCore#258]
I'm having trouble getting this working. I'm using this in a .Net 6 web api, so that it can contract other services with client credentials. I've followed through these instructions https://identitymodel.readthedocs.io/en/latest/aspnetcore/worker.html but my HttpClient doesn't get any authorization, the authorization header is null, and my requests 401 Unauthorized because of this. What am I missing?

Setup:
```
services.AddHttpClient<MyClient>().AddClientAccessTokenHandler();
services.AddAccessTokenManagement(options =>
{
    options.Client.Clients.Add("MyClient", new ClientCredentialsTokenRequest
    {
        Address = settings.ClientCredentials.Domain,
        ClientId = settings.ClientCredentials.ClientId,
        ClientSecret = settings.ClientCredentials.ClientSecret
    });
});
```

Http client implementation:
```
public class MyClient
{
    private readonly HttpClient httpClient;

    public MyClient(HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.httpClient.BaseAddress = new Uri("http://localhost:49153");
    }

    public async Task<IEnumerable<Test>?> GetTests()
    {
        IEnumerable<Test>? tests = await this.httpClient.GetFromJsonAsync<IEnumerable<Test>>("Tests");
        return tests;
    }
}
```

**Comment by leastprivilege** [comment]
I don't know - I would check logging to see if anything gives a hint..

**Comment by mahgo** [comment]
Thanks - can't believe that I didn't think of checking that. I had to extend the ClientAccessTokenManagementService error logging to get more info beyond "Forbidden". I've made a pull request to improve that here: https://github.com/IdentityModel/IdentityModel.AspNetCore/pull/261
