### ISSUE TITLE
Unable to resolve service for type 'AccessTokenManagement.TokenEndpointService' while attempting to activate 'IdentityModel.AspNetCore.AccessTokenManagement.AccessTokenManagementService'.

### ISSUE THREAD

**Issue by code-atom** [IdentityModel/IdentityModel.AspNetCore#26]
Receiving following exception in code:

Unable to resolve service for type 'IdentityModel.AspNetCore.AccessTokenManagement.TokenEndpointService' while attempting to activate 'IdentityModel.AspNetCore.AccessTokenManagement.AccessTokenManagementService'.

Problem resolved by add TokenEndpointService in DI.
```services.AddHttpClient<TokenEndpointService>();```

**Comment by leastprivilege** [comment]
In which code did you add that?

**Comment by code-atom** [comment]
In my local ConfigureService Method in Startup file,

Actually AccessTokenManagementService required TokenEndpointService in constructor and ServiceCollections register with ITokenEndpoint Services.
```services.AddHttpClient<ITokenEndpointService, TokenEndpointService>();```

We need to change **TokenEndpointService** to **ITokenEndpointService** in **AccessTokenManagementService** constructor

**Comment by leastprivilege** [comment]
OK. Done.

thanks!
