### ISSUE TITLE
ClientAccessTokenCache results in error "The absolute expiration value must be in the future. (Parameter 'AbsoluteExpiration')"

### ISSUE THREAD

**Issue by mscherpenisse** [IdentityModel/IdentityModel.AspNetCore#262]
When a token is retrieved from a tokenservice which doesn't have a expires_in defined (this is optional according to the RFC); 
The ClientAccessTokenCache SetAsync function will try to set a cache expiration of -60 seconds which results in the error:

The absolute expiration value must be in the future. (Parameter 'AbsoluteExpiration')

This in combination with the Redis cache provider 

https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/27e966bf6729530e4a7480478f18302fe996a7f6/src/AccessTokenManagement/ClientAccessToken/ClientAccessTokenCache.cs#L72

**Comment by leastprivilege** [comment]
so what should the library do in your opinion then?

**Comment by mscherpenisse** [comment]
If the the value is not set, read it from the token if possible.
If that is not possible, than skip the caching as you don't know how long you can cache the token

**Comment by leastprivilege** [comment]
> If the the value is not set, read it from the token if possible.

this is never possible.

**Comment by leastprivilege** [comment]
OK - I changed the bevavior.

If the token service does not return an expires_in at all - the token will be cached until the resource returns 401.
