### ISSUE TITLE
Support user access to multiple service providers secured with multi tenant IDPs

### ISSUE THREAD

**Issue by milanc** [IdentityModel/IdentityModel.AspNetCore#263]
Hi 
Thank you for starting this library it really simplifies work with external APIs.
I have this use case (from the title) that I think might be common for SaaS applications but as I can see (I might be wrong) that  it is not supported.

I do have working code and usage example in the sample app.
Implementation is partly based on current ClientAccessToken functionality and possibly would replace it but it also manages user access tokens.
Does this feature seems interesting to be part of this library?
Do you want me to create a PR and maybe discuss implementation that I have?

I hope diagram will help me to explain what I am trying to achieve.
Thank you.

![image](https://user-images.githubusercontent.com/8333458/154127426-4073e3f1-7108-4abd-b5b2-89c483631dae.png)

**Comment by leastprivilege** [comment]
Thanks for opening this issue.

I personally do not have that use case, and do currently not have the time to maintain this code. Feel free to take my library as a basis for your own project.

**Comment by milanc** [comment]
I understand, thank you.
