### ISSUE TITLE
ClientCredentialsTokenRequest now using header as ClientCredentialStyle by default

### ISSUE THREAD

**Issue by celia-moreno** [IdentityModel/IdentityModel.AspNetCore#268]
After the upgrade to use the new version of `IdentityModel` nuget implemented in this PR https://github.com/IdentityModel/IdentityModel.AspNetCore/pull/250, which includes this change in the `Identity` nuget: https://github.com/IdentityModel/IdentityModel/pull/429, now the defaut credential style is header. 

This means between the version `4.1.2` and `4.1.3` there is a breaking change.

**Comment by leastprivilege** [comment]
Is that an issue for you?

**Comment by celia-moreno** [comment]
The endpoint we are reaching is throwing exceptions, I can handle it with them, probably they are not ready for that. If not, I can change the style and force it to use the body, but it took me a while to figure it out the reason, as this was minor change I was not expecting a breaking change in my code. Anyone else is suffering same issue?

**Comment by leastprivilege** [comment]
OK - I know what you mean now ;) It got in the way when I upgrade a couple of applications.

I added a flag on the options to set the default credential style.
