### ISSUE TITLE
Default behavior for invalid/expired tokens

### ISSUE THREAD

**Issue by alexvaluyskiy** [IdentityModel/IdentityModel.AspNetCore#27]
What is a default behavior when we got a HTTP response with 401 status from a resource?

The previous version (AccessTokenDelegatingHandler) tried to renew a token first and do an additional HTTP request to a resource.

But the current version - just sets a token from the store and never expire it (only checks `exp` claim)

**Comment by leastprivilege** [comment]
Well - the plumbing tries to make sure that the token is always current - and tried to refresh/request a new one if the current one is expired.. If it can't do that, the application layer has to deal with the 401.

**Comment by alexvaluyskiy** [comment]
I could handle it in the application layer, but in this case I have to reset a cache for this token. Is it possible to do it?

**Comment by leastprivilege** [comment]
Which token are you talking about - user or client?

**Comment by alexvaluyskiy** [comment]
Client token

**Comment by leastprivilege** [comment]
OK - I see. I can add that. Thanks for reporting.

**Comment by leastprivilege** [comment]
I added a delete method on the service/cache.

**Comment by alexvaluyskiy** [comment]
Thanks. I will check it

**Comment by leastprivilege** [comment]
Actually I added a retry behavior for 401s as well. It's not on nuget yet - but check the handler.

**Comment by leastprivilege** [comment]
does it work for you?

**Comment by alexvaluyskiy** [comment]
Yes, it works. Thank you
