### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by coolhome** [IdentityModel/IdentityModel.AspNetCore#28]
What are the milestones for a 1.0.0 release? I would love to help if time permits.

**Comment by leastprivilege** [comment]
No particular milestones..this is still WIP and I am trying to get as much feedback as possible before releasing a 1.0.

So do you have any feedback?

**Comment by coolhome** [comment]
@leastprivilege I've been playing around with the `AccessTokenHandler` in a Asp.net core 2.2 project. I like how you register the client information via `AddOpenIdConnect`.

I ran into some dependency issues for a certain test project of mine.
`IdentityModel.AspNetCore` can be used for `netstandard` and `netcoreapp3`.
`IdentityModel.AspNetCore` requires `IdentityModel@4.0.0` which introduced a lot of breaking changes. 

If I wanted to use `IdentityServer4.AccessTokenValidation@2.7.0` for a .net core 2 project with `IdentityModel.AspNetCore` I would get some runtime errors which can be unexpected. Probably something that should noted.

**Comment by leastprivilege** [comment]
Yes that sounds right. Unfortunate.

**Comment by leastprivilege** [comment]
There's nothing I can do about that right now.  If you have more comments/idea, open a new issue please. thanks!
