### ISSUE TITLE
Processing the id_token during refresh

### ISSUE THREAD

**Issue by janruo** [IdentityModel/IdentityModel.AspNetCore#291]
It would be great if this library processed the id_token received during token refresh and updated the user's claims. Currently the library seems to ignore the id_token completely.

A couple of arguments for this:
1. The user's claims may change after the initial sign in. For example, I'm using a provider that sends an id_token which contains `"picture": "https://example.com/presigned_url_with_expiration"`. The presigned profile picture URL is only valid for a limited time, and a new URL needs to be read from the updated id_token received during token refresh. Other claims like the display name may also change of course.
2. The OIDC spec seems to imply that [if an id_token is present in refresh response, it should be processed](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse)
3. (Kind of a weak argument, but) some badly designed APIs use the id_token as their "access token", even though it's strongly discouraged. Managing the tokens for such an API is currently not possible with this library.

**Comment by janruo** [comment]
Looks like someone else had the same idea a while back (https://github.com/IdentityModel/IdentityModel.AspNetCore/issues/124), but they weren't able to communicate their reasons very clearly.

@leastprivilege Do you have any new thoughts on this?

**Comment by leastprivilege** [comment]
You are not wrong ;) But right now this is not planned from our side.

For your #1 I would recommend using the userinfo endpoint to update the claims when needed rather then tying that to the access token lifetime.
