### ISSUE TITLE
Suggested approach for auto refresh of Access tokens while using oidc client in desktop applications

### ISSUE THREAD

**Issue by shv07** [IdentityModel/IdentityModel.AspNetCore#293]
I have been using the oidc client library for authentication in my desktop application where the user signs in and then the desktop application makes authenticated api calls with the tokens. The samples don't seem to have one for this use case where you won't have a client secret key. What would be the suggested approach here?

**Comment by leastprivilege** [comment]
I am confused how this questions, the subject and the repo fit together. Could you explain?

**Comment by shv07** [comment]
The repo contains samples for worker application where the access token gets renewed behind the scenes and you don't have to do it manually every time you do api calls. I was wondering if it is possible to do the same in the context of a user, with this library.

**Comment by leastprivilege** [comment]
For desktop applications you might want to have a look here:
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples
