### ISSUE TITLE
Upgrade from 3.0 to 4.x completely breaks dynamic configuration

### ISSUE THREAD

**Issue by gingters** [IdentityModel/IdentityModel.AspNetCore#294]
In 3.x the `AccessTokenManagementOptions` were retrieved using the normal options pattern in .NET (Core) / 5+.
With that approach it was possible to have an `IConfigureOptions<AccessTokenManagementOptions>` type to configure the `AccessTokenManagementOptions` at runtime, before they were actually used.

In our case, we have an `AccessTokenManagementConfigureOptions` type that in its `Configure` method determines all the required settings, and sets all required information on the corresponding token client (incl. token endpoint uri).

In 4.x the options aren't used that way anymore, and the client as well as user options are, (allthough they are still named options) taken from the AccessTokenManagementOptions and put as singleton directly to the service collection.

By that change it not possible anymore to use the default .NET configuration / options pattern to use `ConfigureOptions` on the `AccessTokenManagementOptions` and/or the `ClientAccessTokenManagementOptions` specifically. Also, while changing the clients at runtime on the singleton is possible, we can't know when this is being accessed for the first time to provide the dynamic configuration just in time and explicitly before first usage, as it would be easily possible with `IConfigureOptions<T>`.

In our case specifically we also need to use the `IClientAccessTokenManagementService.GetClientAccessTokenAsync(clientName)` manually, as we use that to retrieve an access token to open up a SignalR connection to a server, and that does not use a normal named http client.

So when I call that, it will tell me that `No access token client configuration found for client: {MyClient}`, as I can't provide that in a `IConfigureOptions` at the correct time.

On top of that, if I don't specify my clients name, the `DefaultTokenClientConfigurationService` in 4.x now requires a configured OIDC authentication scheme. This is particularly unwanted, if you have a simple worker process that only needs to authenticate itself against other services, and that is not to be intended to be called in an authenticated fashion (in other words: this is the wrong end, we are not the service that is being called, we are only calling other services, so we don't need authentication schemes here).

So what is the intended upgrade path from 3.0 to 4.x in that case when
  a) authentication schemes should not be provided from a library (as if it used in a web host this could compromise its security), and
  b) configuration needs to be dynamically at runtime, as the service that is to be accessed needs to provide some additional information for all clients before they authenticate?

**Comment by leastprivilege** [comment]
There is no "intended upgrade path". It's free software ;)
