### ISSUE TITLE
Partially public API might end in System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by glatzert** [IdentityModel/IdentityModel.AspNetCore#38]
Hey there, I'm using this fine preview library in conjunction with ProxyKit to automatically manage the access token for requests to the backend.

The backend itself has mutliple endpoints, some of them beeing callable as anonymous.

Startup isn't really interesting, but for completeness:
```
services.AddAccessTokenManagement();
services.AddProxy(httpClientBuilder => {
        httpClientBuilder.AddUserAccessTokenHandler();
});
```

Using the proxy will currently fail with a Exception:

> System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
> Parameter name: value
>    at System.DateTime.Subtract(TimeSpan value)
>    at System.DateTimeOffset.Subtract(TimeSpan value)
>    at IdentityModel.AspNetCore.AccessTokenManagement.AccessTokenManagementService.GetUserAccessTokenAsync() in C:\local\identity\model\IdentityModel.AspNetCore\src\AccessTokenManagement\AccessTokenManagementService.cs:line 110
>    at Microsoft.AspNetCore.Authentication.TokenManagementHttpContextExtensions.GetUserAccessTokenAsync(HttpContext context) in C:\local\identity\model\IdentityModel.AspNetCore\src\AccessTokenManagement\TokenManagementHttpContextExtensions.cs:line 26
>    at IdentityModel.AspNetCore.AccessTokenManagement.UserAccessTokenHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\local\identity\model\IdentityModel.AspNetCore\src\AccessTokenManagement\UserAccessTokenHandler.cs:line 32
>    at [...]

This originates from here https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/cd05423f77af995a658d89606104e002db998c08/src/AccessTokenManagement/AuthenticationSessionUserTokenStore.cs#L44
Where in the case of an unauthenticated user, the UserToken is an empty one.
Which will fail here:
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/cd05423f77af995a658d89606104e002db998c08/src/AccessTokenManagement/AccessTokenManagementService.cs#L113

**Comment by leastprivilege** [comment]
So IOW - `GetUserAccessToken` should immediately return an empty string if the user is not authenticated.

**Comment by glatzert** [comment]
Hm.. probably yes.
If you like I'll rewrite my changes to do that based on the httpContext.User

**Comment by leastprivilege** [comment]
Already done.

**Comment by leastprivilege** [comment]
thanks for reporting

**Comment by glatzert** [comment]
Well, thanks for your module :)
