### ISSUE TITLE
ClientAccessTokenHandler doesn't work outside of http requests

### ISSUE THREAD

**Issue by duckblaster** [IdentityModel/IdentityModel.AspNetCore#46]
The ClientAccessTokenHandler is trying to get the IAccessTokenManagementService from the HttpContext, which is not available outside of an http request.

I would expect it to be getting this from it's constructor instead, as there shouldn't be anything that varies between requests, unlike the UserTokenHandler.

**Comment by leastprivilege** [comment]
Makes sense. In which scenario are you using it outside of an HTTP request?

**Comment by leastprivilege** [comment]
merged

**Comment by vindberg** [comment]
Is this also the case with background services (im using IHostedService). Also getting a null ref error.

Thanks.

**Comment by vindberg** [comment]
Im getting: System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.AspNetCore.Authentication.ISystemClock' while attempting to activate 'IdentityModel.AspNetCore.AccessTokenManagement.AccessTokenManagementService'.'

It seems like its still using some parts of the userclient flow?

startup:

	```
		services.AddClientAccessTokenClientFixed("accounting", client =>
			{
				var url = Configuration.GetValue<string>("AppSettings:AccountingEndpoint");
				client.BaseAddress = new Uri(url);
			});


			services.AddAccessTokenManagementFixed()
			.ConfigureBackchannelHttpClient(client =>
			{
				client.Timeout = TimeSpan.FromSeconds(30);
			});

```

**Comment by leastprivilege** [comment]
@vindberg add

`services.TryAddSingleton<ISystemClock, SystemClock>();`

**Comment by vindberg** [comment]
Yes, that will not work. Then it asks for:

System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.Extensions.Caching.Distributed.IDistributedCache' while attempting to activate 'IdentityModel.AspNetCore.AccessTokenManagement.ClientAccessTokenCache'.'

Im running .net core 2.2.

Can you push out a new nuget with these changes. Then I can try and use it that way.

**Comment by vindberg** [comment]
An update. If I do add the systemclock and distributedcache types (as you did for .net 3.0), then works to some extend.

Now im getting: "No OpenID Connect authentication scheme configured for getting client configuration. Either set the scheme name explicitly or set the default challenge scheme"

Where do I define the clientId and client secret?

**Comment by vindberg** [comment]
Is it something like this? (its not working, but we must be getting closer :) ).

```
			services.AddAccessTokenManagementFixed(options => {
				var clientId = Configuration.GetValue<string>("AppSettings:ClientId");
				var clientSecret = Configuration.GetValue<string>("AppSettings:ClientSecret");

				var clientOptions = new IdentityModel.Client.TokenClientOptions();
				clientOptions.ClientId = clientId;
				clientOptions.ClientSecret = clientSecret;
				var clients = new Dictionary<string, IdentityModel.Client.TokenClientOptions>();
				clients.Add(AccessTokenManagementDefaults.BackChannelHttpClientName, clientOptions);

				options.Client.Clients = clients;
				})
			.ConfigureBackchannelHttpClient(client =>
			{
				client.Timeout = TimeSpan.FromSeconds(30);
			});

```

**Comment by leastprivilege** [comment]
Well - this is only for OIDC enabled applications. For worker services you would not do it like that.

**Comment by leastprivilege** [comment]
Here's a worker example

https://github.com/IdentityModel/IdentityModel.AspNetCore/tree/master/samples/WorkerService

**Comment by vindberg** [comment]
Thanks for the example, I tried that earlier without success. Yours works!

For dotnet 2.2, I also needed to add services.AddDistributedMemoryCache();

Thanks.
