### ISSUE TITLE
Error requesting access token for client default. Error = invalid_scope

### ISSUE THREAD

**Issue by webbes** [IdentityModel/IdentityModel.AspNetCore#55]
I do not understand where this error is coming from. The App1 receives this message when executing a request towards App3

Error requesting access token for client default. Error = invalid_scope

The token server generated the following error:
IdentityServer4.Validation.TokenRequestValidator[0]
      Client cannot request a refresh token in client credentials flow{ clientId = 709038.App1}, details: {
        "ClientId": "709038.App1",
        "ClientName": "App1",
        "GrantType": "client_credentials",
        "Scopes": "709038.App2.api 709038.App1.api address email multi-tenant.App3.api offline_access openid profile role",
        "Raw": {
          "grant_type": "client_credentials",
          "client_id": "709038.App1",
          "client_secret": "***REDACTED***"
        }
      }

The question is: why is it requesting offline_access and thus a refresh token? It indeed does not make sense to do so it seems. Same goes for address email and profile btw. Is there a way to configure the requested scopes specifically for when fetching a Client token?

I've simple configured it like this:
services.AddAccessTokenManagement()
                .ConfigureBackchannelHttpClient()
                    .AddTransientHttpErrorPolicy(policy => policy.WaitAndRetryAsync(new[]
                    {
                        TimeSpan.FromSeconds(1),
                        TimeSpan.FromSeconds(2),
                        TimeSpan.FromSeconds(3)
                    }));

            services.AddHttpClient(HttpClientNames.UserAccessDoNotRetry)
                    .AddUserAccessTokenHandler();

            services.AddHttpClient(HttpClientNames.ClientAccessDoNotRetry)
                    .AddClientAccessTokenHandler();

UserAccess works perfect

**Comment by leastprivilege** [comment]
How is your OpenID Connect handler configured?

**Comment by leastprivilege** [comment]
I am not quite sure why you are getting this error - but this uncovered an interesting problem - so I added a config switch to set the scopes explicitly for client tokens.

**Comment by webbes** [comment]
Sorry for my late reply, but thank you very much! Really don't feel comfortable of making code changes to AuthN AuthZ software as I'm not 100% sure about what I know and don't know. And you are able to solve these things so fast... respect.
