### ISSUE TITLE
GetUserAccessTokenAsync(bool forceRenewal = false) throws when the store does not have an existing token

### ISSUE THREAD

**Issue by webbes** [IdentityModel/IdentityModel.AspNetCore#56]
"var dtRefresh = userToken.Expiration.Subtract(_options.User.RefreshBeforeExpiration);"

throws an exception because the default value of Expiration == DateTime.MinValue of which you cannot subtract anything as this would result in an invalid DateTime object.

**Comment by leastprivilege** [comment]
Added a more defensive check. Does that work for you?

https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/6235dfdfe6bf73d6d69afb1d3344c9bdaf85d4c9/src/AccessTokenManagement/AccessTokenManagementService.cs#L118-L122

**Comment by webbes** [comment]
Sorry for my late reply. But yes, that would do perfectly fine.
