### ISSUE TITLE
Default value for ClientCredentialStyle should be ClientCredentialStyle.AuthorizationHeader

### ISSUE THREAD

**Issue by vit100** [IdentityModel/IdentityModel.AspNetCore#59]
By default when client request is constructed ClientCredentialStyle set to Body: 
```
//ProtocolRequest.cs
//line 65
public ClientCredentialStyle ClientCredentialStyle { get; set; } = ClientCredentialStyle.PostBody;
```

According to spec: [https://tools.ietf.org/html/rfc6749#section-2.3.1](https://tools.ietf.org/html/rfc6749#section-2.3.1) 

> Including the client credentials in the request-body using the two
   parameters is NOT RECOMMENDED and SHOULD be limited to clients unable
   to directly utilize the HTTP Basic authentication scheme (or other
   password-based HTTP authentication schemes). 

Should default setting be `ClientCredentialStyle.AuthorizationHeader`?

**Comment by leastprivilege** [comment]
I think the main reason we default to the body is that most implementations use the wrong encoding for the header. We are doing it correctly.

But yeah - maybe it is time to re-visit this. It's a breaking change though.

**Comment by vit100** [comment]
Yes, you are doing correctly UrlEncoding of id:pass in header. 

Btw famous Postman has bug with this and it is logged [here](https://github.com/postmanlabs/postman-app-support/issues/7138).

I don't think it is breaking change as according to spec, auth server must support receiving credentials both ways - in header and in body. So I would say it is more issue with auth server if app stops working -)).
