### ISSUE TITLE
User.IsAuthenticated is false in OnValidatePrincipal

### ISSUE THREAD

**Issue by DaleyKD** [IdentityModel/IdentityModel.AspNetCore#64]
```
options.Events.OnValidatePrincipal = async e =>
{
    var currentToken = await e.HttpContext.GetUserAccessTokenAsync();

    if (string.IsNullOrWhiteSpace(currentToken))
    {
        e.RejectPrincipal();
    }
};
```
In this code snippet, calling `GetUserAccessTokenAsync()` always returns null because `HttpContext.User.IsAuthenticated` is false.  However, `e.Principal` is fully populated with the proper principal/claims/etc.

**Comment by leastprivilege** [comment]
hm - the session is probably not populated at this point - that why there is nothing to return.

Why are basing the cookie lifetime on the existence of an access token?

**Comment by DaleyKD** [comment]
I was just using the example provided at:
https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Clients/src/MvcAutomaticTokenManagement/Startup.cs

And the next one followed suit:
https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Clients/src/MvcHybridAutomaticRefresh/Startup.cs

Except that one uses an early version of this repo's code, and it uses its own `CookieAuthenticationEvents` but it doesn't do a check for the user on the `HttpContext`.

**Comment by DaleyKD** [comment]
I had hoped that I could just add a new overload to `IAccessTokenManagementService` that looked like `Task<string> GetUserAccessTokenAsync(ClaimsPrincipal principal, bool forceRenewal = false);` .  Then I'd use that principal in lieu of `HttpContext.User` .

However, when it got to `var userToken = await _userTokenStore.GetTokenAsync(user);` (where user is from the `CookieValidatePrincipalContext.Principal`), it just stopped debugging.

I can't look at it anymore this week due to the end of the sprint.  I can try to look into it again in a week or so.

If you want more information, let me know.

In my client, I'm using ASP.NET Core Identity, and then using `AddOpenIdConnect` to connect to IdentityServer4 v3.0.2 and  .NET Core 3.1.1.

**Comment by DaleyKD** [comment]
More info.  It appears that the reason `AuthenticationSessionUserTokenStore.GetTokenAsync` is crashing is a `StackOverflowException.`  When it calls `await _contextAccessor.HttpContext.AuthenticateAsync();`, it triggers the Cookie event `ValidatePrincipal` again.  An infinite loop ensues.

**Comment by DaleyKD** [comment]
I used the code out of https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients/src/MvcHybridAutomaticRefresh/AutomaticTokenManagement for today.

In order to get it to work, I had to set `context.ShouldRenew = true;` before the `SignInAsync` in `AutomaticTokenManagementCookieEvents`.
