### ISSUE TITLE
Is it possible to use authority address in AccessTokenManagement service.

### ISSUE THREAD

**Issue by vit100** [IdentityModel/IdentityModel.AspNetCore#65]
Question.
When configuring AccessTokenManagementService it is necessary to provide token endpoint
```
services.AddAccessTokenManagement(o =>{

                o.Client.Clients.Add(new ClientCredentialsTokenRequest()
                {
                    Address = <TOKEN-END-POINT>
                });
            });
```

It could be more convenient to use authority address instead. Internally it could use `IDiscoveryCache` to retrieve token endpoint..

Idea is to minimize configuration of the application and use only one config item - `authorityUrl`.
All others items can be fetched from `.well-know`.

Otherwise need to provide authority - for DiscoveryService, tokenEndpoit for above, etc...

**Comment by leastprivilege** [comment]
Not right now.

**Comment by cristiango** [comment]
@leastprivilege Will a PR change your mind?

**Comment by leastprivilege** [comment]
You can use DiscoveryCache (e.g. as a static type) - or I recently introduced a config service, so you could resolve the actual endoint at runtime.

**Comment by ngbrown** [comment]
I think this was the only major stumbling block I hit when integrating `IdentityModel.AspNetCore`.

The `Authority` is a well-known configuration string across the various services, so it's a little awkward to have to add `/connect/token` to it.
```cs
new ClientCredentialsTokenRequest {
    Address = credentialsOptions.Authority + "/connect/token",
};
```

Ideally `DiscoveryCache` is somehow integrated with this.

**Comment by ngbrown** [comment]
I didn't understand what this meant:

> I recently introduced a config service, so you could resolve the actual endoint at runtime.

I don't see a way to set the `Address` through an asynchronous method.

**Comment by leastprivilege** [comment]
I think this problem is solved now.
