### ISSUE TITLE
Add IServiceProvider in .AddAccessTokenManagement()

### ISSUE THREAD

**Issue by vit100** [IdentityModel/IdentityModel.AspNetCore#66]
Current implementation 
`       public static TokenManagementBuilder AddAccessTokenManagement(this IServiceCollection services, Action<AccessTokenManagementOptions> options = null)
 `

Can it be changed/added another overload with this signature:
`       public static TokenManagementBuilder AddAccessTokenManagement(this IServiceCollection services, Action<IServiceProvider, AccessTokenManagementOptions> options = null)`
 
Reason:

I need to provide `ClientAssertion` value builder and would like to have there DI created object.

 ```
services.AddAccessTokenManagement(o =>
            {
                o.Client.Clients.Add("tokenClient_privateKeyJwt", new ClientCredentialsTokenRequest()
                {
                    Address = "tokenEndpoint",
                    ClientAssertion = new ClientAssertion()
                    {
                        Type = OidcConstants.ClientAssertionTypes.JwtBearer,
                        Value= TokenBuilder.GetToken() //static method. not good.
// Instead would be nice to have serviceProvider.GetRequiredService<TokenBuilder>.GetToken()
                    }
                });
            });

```

**Comment by carlin-q-scott** [comment]
I'd like this feature so that I can supply appsettings rather than hardcoded settings as shown in all of the examples that I've seen.
