### ISSUE TITLE
AddAccessTokenManagement doesn't recalculate ClientAssertion.Value.

### ISSUE THREAD

**Issue by vit100** [IdentityModel/IdentityModel.AspNetCore#69]
Problem with token client and ClientAssertion method.
This is how token management registered:
```
services.AddAccessTokenManagement(o =>
            {
                var tokenGenerator= services.BuildServiceProvider().GetRequiredService<PrivateKeyJwtTokenGenerator>();
                o.Client.Clients.Add(new ClientCredentialsTokenRequest
                {
                    Address = TokenEndpoint,
                    ClientAssertion = new ClientAssertion()
                    {
                        Type = OidcConstants.ClientAssertionTypes.JwtBearer,
                        Value = tokenGenerator.CreateClientAuthJwt()
                    }
                });
            });

```

It works... till token expires. AccessTokenManagement is trying to fetch new token - it is good, but!
`ClientAssertion` property is holding same object. 

Problem here is that ClientAssertion.Value  has same JWT as with initial request. It is not good, as this JWT is created with unique `jti` claim, and it means that this jwt supposed to be used only once.
[https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)
As result token server rejects request for another token.

**Comment by leastprivilege** [comment]
OK - interesting.

Yea - so I guess this (and other discussions I had) point to the fact that the config system needs to be extensible.

Need to think about it.

**Comment by vit100** [comment]
I think in this particular case it is more bug then enhancement

**Comment by leastprivilege** [comment]
It's not a bug. It behaves exactly how I designed it.

**Comment by vit100** [comment]
all right, 
Can I do PR with enhancement for this authentication type? Will you approve it?
I did small change in ClientAssertion class - I added property
`public Func<string> ValueProvider { get; set; }`

and in `IdentityModel.Client.ProtocolRequest.Prepare()` I check if ValueProvider set and if value exists it will take priority over Value.
By this I force to recalculate Value - delegate will recreate  private key jwt (with new jti).

I will create PR, pls have a look.

**Comment by leastprivilege** [comment]
Hey, 

I took a different approach. I made the configuration pluggable, this means you can dynamically return the client config including the assertion.

This might need a bit more polish - but here is the commit
https://github.com/IdentityModel/IdentityModel.AspNetCore/commit/1523c767bc60edc17868837e9cdc3578050d7c03

**Comment by vit100** [comment]
Hi Dominick,
Well, it is good that configuration service is abstracted now.
Now questions:
1. Now `public async Task<ClientCredentialsTokenRequest> OptionsTokenClientConfigurationService.GetClientCredentialsRequestAsync()` is in external service. How consumer supposed to change `ClientCredentialsTokenRequest` response of this method (I need to set new value into `requestDetails.ClientAssertion.Value = "HERE I NEED recalculate value"`)? By creating new implementation of `ITokenClientConfigurationService`? Too much.
Or by inheriting OptionsTokenClientConfigurationService and override `GetClientCredentialsRequestAsync()`? Then it should be virtual. 
In any case it should be separately registered `            services.AddTransient<ITokenClientConfigurationService, MyOptionsTokenClientConfigurationService>();`, right?

2. this commit [1523c76](https://github.com/IdentityModel/IdentityModel.AspNetCore/commit/1523c767bc60edc17868837e9cdc3578050d7c03) has NotImplemented on purpose?
```
 public Task<TokenRevocationRequest> GetTokenRevocationRequestAsync()
        {
            throw new System.NotImplementedException();
        }
```

**Comment by leastprivilege** [comment]
Yes. Looks good.

**Comment by vit100** [comment]
Well... Your library, your rules...
I will cancel my or.
What abt notimplemented method?

Can you push the latest code to nuget, pls?

**Comment by leastprivilege** [comment]
done
