### ISSUE TITLE
.Net Core 2.1 compatibility question

### ISSUE THREAD

**Issue by alexey62soft** [IdentityModel/IdentityModel.AspNetCore#72]
Hello!

Looks like we need to add Distributed Caching manually in .Net Core 2.1 applications according to this line: [TokenManagementServiceCollectionExtensions.cs](https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/TokenManagementServiceCollectionExtensions.cs#L31-L33)

From my perspective, would be better to support the .Net Core 2.1 version too because it is an LTS version.

**Comment by leastprivilege** [comment]
I will probably drop 2.1 support before release. Not really interested in testing on old versions.

**Comment by alexey62soft** [comment]
This LTS version still used on various projects.
It works well with 2.1 - we just need to add this call manually.

**Comment by leastprivilege** [comment]
OK. thanks
