### ISSUE TITLE
AccessTokenManagementService exception management

### ISSUE THREAD

**Issue by bordecal** [IdentityModel/IdentityModel.AspNetCore#73]
In its current implementation, `AccessTokenManagementService` suppresses problems encountered when trying to obtain a token.  e.g.: https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/58faaa2241a2ef4e847d13d35057bfe8f0b75b09/src/AccessTokenManagement/AccessTokenManagementService.cs#L82-L86

This can make it difficult for consuming developers to identify the cause of failures that occur when performing HTTP requests that should have been (but are not) decorated with authorization headers.

Is there a use case for suppressing these problems instead of throwing exceptions?  If so, might it worthwhile to throw by default and add an option to allow suppression when it is actually desirable?

**Comment by leastprivilege** [comment]
How would you recover at runtime from such an exceptional condition.

Or is it only about not having to look at log files?

**Comment by bordecal** [comment]
The only meaningful way to attempt recovery in my current use case would be to try fetching new credentials for the token manager to use, which could potentially result in acquisition of newly valid credentials.  Attempting to trigger such logic from the code that eventually fails because of a missing authorization token under the current approach is certainly possible, but it strikes me as  sub-optimal (amongst other things, it creates a rather leaky abstraction around the token management).

There's also the issue of usability of the log information.  It won't necessarily be noticed by many developers during initial development, which will lead to prolonged troubleshooting efforts to diagnose a problem that would have been very simple to locate if an exception had been thrown.  Annoying as that might be to some, the potential usability of the production runtime information is perhaps a more serious issue.  For systems that generate large quantities of log information (for example, due to heavy traffic and/or routinely problematic integrations), the log entry generated by IdentityModel may end up being separated from the eventual HTTP request failure error by many  intervening entries.  It may be quite difficult for production support operators to identify that the entries are related, which will result in prolongation of troubleshooting efforts at a time when a production system is encountering a potentially critical failure.

**Comment by leastprivilege** [comment]
So yea - any problem with the token request will return "nothing" which ultimately (after a retry) will result in a 401. That's what tells you that something is wrong, and it *might* be fixed by trying "new credentials".

**Comment by bordecal** [comment]
Yup.  But how does someone who isn't familiar with the library make that connection?

It seems to me that it might make more sense to throw by default when the token request fails.  This would enable cleaner handling of the problem, as well as facilitating troubleshooting.  If there are compelling use cases for eating the exception, then adding a configuration element for opting out of the throw (i.e.: logging instead of throwing, as is the current behaviour) wouldn't be terribly difficult.

**Comment by leastprivilege** [comment]
I personally don't like that I have to do exception handling and check for the 401...

I guess that's the definition of "opinionated" ?
