### ISSUE TITLE
Proper refresh token approach

### ISSUE THREAD

**Issue by bigdnf** [IdentityModel/IdentityModel.AspNetCore#79]
In version 4.0 of IdentityModel RefreshTokenDelegatingHandler and AccessTokenDelegatingHandler was removed with comment in release notes “I never was happy with their design, and they also did not work for some common scenarios”.  
As I understand right this repo now contains ASP.NET part of the project so I have a question what is the problem with that implementation and what is suggested approach to do that in ASP.NET Core with IdentityModel? I can se ClientAccessTokenHandler but token is retrieved every request (no cache) and I’m wonder about performance.

**Comment by leastprivilege** [comment]
It is cached. Try the sample.

**Comment by bigdnf** [comment]
Ok I overlooked some stuff. Thanks for clarification.

**Comment by bigdnf** [comment]
Library have token managment in place
