### ISSUE TITLE
Will there be support for other TokenRequests?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityModel/IdentityModel.AspNetCore#80]
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/AccessTokenManagementOptions.cs#L71

Why not any of these? https://github.com/IdentityModel/IdentityModel/blob/master/src/Client/Messages/TokenRequest.cs

**Comment by leastprivilege** [comment]
What's the use case?

**Comment by VictorioBerra** [comment]
I thought about it more. Probably nothing worth making the changes. I think I will just implement my own ITokenEndpointService.

**Comment by VictorioBerra** [comment]
Just to follow up on this. A usecase for me is the Resource Owner Flow, I need to refresh my token and I cannot use _httpContextAccessor.HttpContext.User.

I would like a way to provide my own `userToken` and not have to pull it from the http context.

**Comment by leastprivilege** [comment]
There is already a user token store abstraction.
