### ISSUE TITLE
Issue with Auth0 and refresh tokens

### ISSUE THREAD

**Issue by markgould** [IdentityModel/IdentityModel.AspNetCore#90]
I'm getting the error "No refresh token found in cookie properties. A refresh token must be requested and SaveTokens must be enabled."

I've looked at the Auth0 docs and it appears they don't return the refresh_token upon refreshing the access token. You can see the response section here: https://auth0.com/docs/tokens/guides/use-refresh-tokens.

It looks like this could be fixed here:

https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/486f6fc7137bb1f4cb1a7041d70e99ac7a1a17d4/src/AccessTokenManagement/AccessTokenManagementService.cs#L172

By changing:

`await _userTokenStore.StoreTokenAsync(_httpContextAccessor.HttpContext.User, response.AccessToken, response.ExpiresIn, response.RefreshToken);`

To:

`await _userTokenStore.StoreTokenAsync(_httpContextAccessor.HttpContext.User, response.AccessToken, response.ExpiresIn, response.RefreshToken ?? userToken.RefreshToken);
`

If this is acceptable to you, I can submit a PR. If you'd prefer it be on some sort of flag, I can look into that too.

Also from the Auth0 docs (https://auth0.com/docs/tokens/concepts/refresh-tokens)

> A Refresh Token is a special kind of token that can be used to obtain a renewed access token. You are able to request new access tokens until the Refresh Token is blacklisted. It’s important that refresh tokens are stored securely by the application because they essentially allow a user to remain authenticated forever.

**Comment by leastprivilege** [comment]
OK - sounds reasonable. Please do a PR.
