### ISSUE TITLE
Support for PasswordTokenRequest or any TokenRequest

### ISSUE THREAD

**Issue by Adriien-M** [IdentityModel/IdentityModel.AspNetCore#92]
For some cases, `client_credentials` flow is not enough.
Maybe, for Worker Applications, in the same way as you support `ClientCredentialsTokenRequest`, it should be cool to handle `PasswordTokenRequest` as well?

Maybe to be more generic, the Clients dictionary in [AccessTokenManagementOptions](https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/AccessTokenManagementOptions.cs) could be a `IDictionary<string, T>` where `T` is a any  `TokenRequest`?

**Comment by leastprivilege** [comment]
No - password grant type is not recommended. I won't add support for it.

**Comment by Adriien-M** [comment]
Alright, can you tell me why it is not recommended? Even in internal network from machine to machine?

**Comment by VictorioBerra** [comment]
> internal network from machine to machine

This is exactly what Client Credentials is for.

> This flow provides no mechanism for things like multifactor authentication or delegated accounts, so is quite limiting in practice. [The latest OAuth 2.0 Security Best Current Practice disallows the password grant entirely.](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-3.4) - VIA https://oauth.net/2/grant-types/password/

You can also just implement any of the interfaces here you want and then register it with DI before you add token management. For example, just implement this: 
https://github.com/IdentityModel/IdentityModel.AspNetCore/blob/master/src/AccessTokenManagement/TokenEndpointService.cs
