### ISSUE TITLE
Userinfo claims update

### ISSUE THREAD

**Issue by Demonell** [IdentityModel/IdentityModel.AspNetCore#97]
That would be nice to have option to update user claims (as an example via request to connect/userinfo) when we update access_token (via AddAccessTokenManagement). Or option to update idToken also (because it can have user claims too).

**Comment by leastprivilege** [comment]
Thanks. Need to think about that.

Leaving this open as a reminder.

**Comment by leastprivilege** [comment]
this is out of scope for this library.
